# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 🪿

on:
  workflow_run:
    workflows: ["PR"]
    types: ["completed"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests"

# on:
#   push:
#     branches: main
#   pull_request:
#   workflow_dispatch: # Manual runs

# env:
#   PROJECT: jss-22p1-test
#   WORKLOAD_IDENTITY_PROVIDER: projects/886556137211/locations/global/workloadIdentityPools/github-actions/providers/github-actions-python

# jobs:
#   affected:
#     name: Finding affected tests
#     runs-on: ubuntu-latest
#     outputs:
#       python: ${{steps.python.outputs.affected}}
#     defaults:
#       run:
#         working-directory: .github/testing
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - uses: oven-sh/setup-bun@v2
#       - run: bun install
#       - id: python
#         run: |
#           AFFECTED_PYTHON=$(bun run affected python HEAD origin/main)
#           echo "$AFFECTED_PYTHON"
#           echo "affected=$AFFECTED_PYTHON" >> "$GITHUB_OUTPUT"

#   python-lint:
#     name: Lint Python
#     needs: affected
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         affected: ${{fromJson(needs.affected.outputs.python)}}
#     defaults:
#       run:
#         working-directory: .github/testing
#     steps:
#       - uses: actions/checkout@v4
#       - uses: oven-sh/setup-bun@v2
#       - uses: actions/setup-python@v5
#         with:
#           python-version: '3.12'
#       - run: pip install nox
#       - run: bun install
#       - run: bun run ci-lint python AFFECTED
#         env:
#           AFFECTED: ${{toJson(matrix.affected)}}

#   python-test:
#     name: Test Python
#     needs: affected
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
#         affected: ${{fromJson(needs.affected.outputs.python)}}
#     permissions: # needed for google-github-actions/auth
#       id-token: write
#       contents: read
#     defaults:
#       run:
#         working-directory: .github/testing
#     steps:
#       - uses: actions/checkout@v4
#       - uses: oven-sh/setup-bun@v2
#       - uses: actions/setup-python@v5
#         with:
#           python-version: ${{matrix.python-version}}
#       - uses: 'google-github-actions/auth@v2'
#         with:
#           project_id: ${{env.PROJECT}}
#           workload_identity_provider: ${{env.WORKLOAD_IDENTITY_PROVIDER}}
#       - run: pip install nox
#       - run: bun install
#       - run: bun run ci-test python${{matrix.python-version}} AFFECTED
#         env:
#           AFFECTED: ${{toJson(matrix.affected)}}
